version: '3.7'

services:
  fan_control:
    container_name: fan_control
    hostname: fan_control
    restart: unless-stopped

    image: fan_control
    build:
      context: .


    # $$$  TODO:: RUN NOT AS ROOT --> Requires groups 'gpio' & 'video' --> groupadd ???  $$$
    # user: "$PUID:$PGID"

    # Reference: https://stackoverflow.com/a/48234752
    devices:
      - /dev/gpiomem
      - /dev/vchiq

    volumes:
      - /sys:/sys


    network_mode: "none"

    env_file:
      - .env

    labels:
     # Watchtower
      - "com.centurylinklabs.watchtower.enable=false"
